### ISSUE TITLE
Allow Postgres

### ISSUE THREAD

**Issue by tacman** [j0k3r/f43.me#1083]
I think the only issue preventing this project from using PostgreSQL is the custom DATE DQL.

One solution is to drop the custom function, e.g.

```php
$dateTime = new \DateTime();
$qb
   ->andWhere('jobs.endDate BETWEEN :dateMin AND :dateMax')
   ->setParameters(
       [
            'dateMin' => $dateTime->format('Y-m-d 00:00:00'),
            'dateMax' => $dateTime->format('Y-m-d 23:59:59'),
       ]
    );
```

from https://stackoverflow.com/questions/25883616/how-can-i-use-date-in-doctrine-2-dql/50236819#50236819

My original motivation for PostgreSQL instead of MySQL was the free 10k row database Heroku provides, but they're discontinuing that later this year.  Still, I like postgres better for anything with JSON fields, and I find their full-text search acceptable.  Perhaps that's true with MySQL as well.

**Comment by j0k3r** [comment]
I'm not against allowing Postgres.
Maybe that DQL functions aren't necessary anymore. I added it back in 2019 when I rewrote the model from Mongo to MySQL.
Feel free to remove it to test if it's ok with Postgres.
