### ISSUE TITLE
Graby ignores the http_header(user-agent)

### ISSUE THREAD

**Issue by rlandolt** [j0k3r/f43.me#1307]
I've tried it on https://f43.me/feed/test#

URL to request: https://www.whatsmyua.info/
Want to try a custom siteconfig => http_header(user-agent): "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

But the returned page says 
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.92 Safari/535.2"

**Comment by j0k3r** [comment]
You're right, it's a problem related to permission on the server (nothing to do with the code itself).
<img width="606" alt="image" src="https://github.com/j0k3r/f43.me/assets/62333/9271072b-936e-43ba-a73f-7e4ffe2e793c">

Maybe the way we temporary store the site config file should be improved.
