### ISSUE TITLE
403 Bad Behavior on blog.gnome.org, amongst others

### ISSUE THREAD

**Issue by shtrom** [j0k3r/f43.me#170]
Trying to parse https://blogs.gnome.org/aday/2017/08/08/the-gnome-way/ on https://f43.me/feed/test fails.

Looking in the debug log, this stands out:

    Client error response [url] https://blogs.gnome.org/aday/2017/08/08/the-gnome-way/?not-changed [status code] 403 [reason phrase] Bad Behavior

Hitting the link manually in the browser just work, so I'm not sure what's different here.

I have also seen this happen on other sites which are presumably running the same stack (e.g., https://www.happyassassin.net/2014/01/25/uefi-boot-how-does-that-actually-work-then/?not-changed) (Wordpress?)

**Comment by j0k3r** [comment]
Looks weird.
Maybe we should try to use a custom user-agent, or sth to avoid that 403

**Comment by j0k3r** [comment]
Now you know how to fix that kind of error ☝️

**Comment by shtrom** [comment]
Cool cheers. So, just a user-agent issue?

**Comment by j0k3r** [comment]
Yup

**Comment by shtrom** [comment]
Has this been pushed to f43.me? I still get a 403 on both sites.

**Comment by j0k3r** [comment]
Not yet
