### ISSUE TITLE
f43.me - connection refused

### ISSUE THREAD

**Issue by 4oo4** [j0k3r/f43.me#177]
Getting a Connection Refused error when trying to go to f43.me today. I'm assuming it's maintenance related but wanted to mention something.

Cheers

**Comment by j0k3r** [comment]
It's not really a maintenance. The whole server is down, I just need to get it back.
I'm talking with my hosting provider atm.

**Comment by j0k3r** [comment]
Hard drive is dead.
It'll took some time to rebuild the server :disappointed:

**Comment by 4oo4** [comment]
Ahh that's no fun. Thanks for the update

**Comment by 4oo4** [comment]
I can see that it's back up now, thanks!

**Comment by j0k3r** [comment]
Yup, might not fully work but it's up!
