### ISSUE TITLE
TestLink tool seems not to use my SiteConfig

### ISSUE THREAD

**Issue by slavniyteo** [j0k3r/f43.me#193]
Hi. Thank you for your work (again, I've already created an issue at the wallabag/wallabag few days ago).

I try to create a site config for [this page](https://www.opennet.ru/opennews/art.shtml?num=49565) at the [test link page](https://f43.me/feed/test). The problem is the parser catches the comments instead of the article. I checked with curl that article isn't downloaded via javascript and present in initial page sources.

I've created a test config [here](http://siteconfig.fivefilters.org/) for example:
```
body: //td[@id='r_memo']
test_url: https://www.opennet.ru/opennews/art.shtml?num=49565
```

It looks that any mutation of this config doesn't mention the parsing result.

When I click "Test", It clears the fields *body* and *test_url* and prints the same output as always.

**Comment by j0k3r** [comment]
Are you using the internal parser?
If so, they might have a bug when merging site_config when a site_config already exists.

**Comment by techexo** [comment]
Indeed, I used the internal parser, and looking at the detailed information, I can see that the parser uses the existing config but not the custom one.
I tried using Firefox with and without ad-block and tested it on Vivaldi (Chromium engine) to ensure that it was not just a form issue, but to no avail.

Any idea on how to fix this?

**Comment by j0k3r** [comment]
This isn't a problem on the browser, I guess it's how site_config are merged

**Comment by j0k3r** [comment]
There were indeed a problem.
It’s fixed now https://github.com/j0k3r/f43.me/pull/199
