### ISSUE TITLE
 Docker image build error

### ISSUE THREAD

**Issue by ofury** [j0k3r/f43.me#313]
unable to build without errors using docker-compose:

Step 12/15 : RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php
     && php -r "unlink('composer-setup.php');"     && mv composer.phar /usr/sbin/composer
 ---> Running in a7d3efe7a532

Warning: copy(https://getcomposer.org/installer): failed to open stream: Cannot assign requested address in Command line code on line 1

Call Stack:
    0.0000     386728   1. {main}() Command line code:0
    0.0001     386728   2. copy() Command line code:1

Could not open input file: composer-setup.php
ERROR: Service 'nginx-php7.2' failed to build: The command '/bin/sh -c php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php     && php -r "unlink('composer-setup.php');"     && mv composer.phar /usr/sbin/composer' returned a non-zero code: 1

**Comment by j0k3r** [comment]
Did you modify sth on the docker images?
It looks likes PHP can't access the website which means it got restricted (firewall or bad configuration).
