### ISSUE TITLE
No debug logs on "Test Link" page

### ISSUE THREAD

**Issue by odahoda** [j0k3r/f43.me#755]
I'm trying to debug some issues with wallabag, but https://f43.me/feed/test is not helpful.
E.g. for https://knowablemagazine.org/article/society/2021/role-of-political-parties-democracy it just tells me that it fails, but the "Debug Logs" tab is empty.
I vaguely remember that I used that in the past and it was a lot more chatty...

**Comment by j0k3r** [comment]
As far as I remember I disabled it few weeks ago because it generated huge log files (like ~100Go).
I'll check it to re-enable it and setup a proper log rotate

**Comment by j0k3r** [comment]
As far as I remember I disabled it few weeks ago because it generated huge log files (like ~100Go).
I'll check it to re-enable it and setup a proper log rotate

**Comment by j0k3r** [comment]
It's back
