### ISSUE TITLE
Update docker files

### ISSUE THREAD

**Issue by tacman** [j0k3r/f43.me#823]
I've installed docker-ce, and pulled the repo.  When I run docker-compose up, I get the following:

```
nginx-php7.2_1  | In Connection.php line 108:
nginx-php7.2_1  |                                                                                
nginx-php7.2_1  |   You cannot use the "Symfony\Component\Messenger\Bridge\Amqp\Transport\Conne  
nginx-php7.2_1  |   ction" as the "amqp" extension is not installed.                             
nginx-php7.2_1  |                                                                                
nginx-php7.2_1  | 
nginx-php7.2_1  | doctrine:schema:create [--em EM] [--dump-sql]
nginx-php7.2_1  | 
nginx-php7.2_1  | 2021-11-17T13:22:07+00:00 [info] User Deprecated: Since doctrine/doctrine-bundle 2.4: The "connection_override_options" connection parameter is deprecated
nginx-php7.2_1  | Ready 🚀 http://localhost:8100/app_dev.php/
```

I'm new to docker, so I'm not sure how to fix this.  The fact that it's directing to app_dev.php indicates that it's an older version of Symfony.  Digging around a little bit, I also see that it's copying parameters.yml, also old.

I was also hoping that this whole project could be updated to at least PHP 7.4, but php8.0 would be even better.

The main reason I want to use docker is because I don't have MySQL and Mercure installed locally, so though that this would be a good time to use docker.

**Comment by j0k3r** [comment]
That's right, Docker images are outdated. They need to be updated
